version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Data Source=API/db.db;"
  db:
    image: "sqlite:latest"
    container_name: "sqlite"
    volumes:
      - ./Data:/data
